FROM php:7.2-apache
RUN apt-get update

# 1. development packages
RUN apt-get install -y \
 git \
 zip \
 curl \
 sudo \
 libcurl4-openssl-dev \
 pkg-config \
 libssl-dev \
 unzip \
 libicu-dev \
 libbz2-dev \
 libpng-dev \
 libjpeg-dev \
 libmcrypt-dev \
 libreadline-dev \
 libfreetype6-dev \
 g++ \
 libfreetype6-dev \
        libjpeg62-turbo-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd  

# 2. apache configs + document root
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf
RUN sed -ri -e "s!/var/www/!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
# 3. mod_rewrite for URL rewrite and mod_headers for .htaccess extra headers like Access-Control-Allow-Origin-
RUN a2enmod rewrite headers
# 4. start with base php config, then add extensions
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

RUN docker-php-ext-install \
 bz2 \
 intl \
 iconv \
 bcmath \
 opcache \
 calendar \
 mbstring \
 pdo_mysql \
 zip

WORKDIR /var/www/html

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install

RUN chown -R www-data: /var/www/html
RUN  php artisan key:generate


